# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dominicana": "02_Data_preparation.ipynb",
         "etp": "02_Data_preparation.ipynb",
         "get_independent_vars": "02_Data_preparation.ipynb",
         "independent_vars_to_targs": "02_Data_preparation.ipynb",
         "drop_last_value": "02_Data_preparation.ipynb",
         "get_target": "02_Data_preparation.ipynb",
         "get_clan_membership": "02_Data_preparation.ipynb",
         "merged_datasets": "02_Data_preparation.ipynb",
         "get_ETP_independent_vars": "02_Data_preparation.ipynb",
         "dblock_pretrain": "02_Data_preparation.ipynb",
         "datasets_pretrain": "02_Data_preparation.ipynb",
         "mask": "02_Data_preparation.ipynb",
         "dominicana_clean": "02_Data_preparation.ipynb",
         "dominicana_clan": "02_Data_preparation.ipynb",
         "dblock_train": "02_Data_preparation.ipynb",
         "datasets_clan": "02_Data_preparation.ipynb",
         "get_coda_type": "02_Data_preparation.ipynb",
         "datasets_coda": "02_Data_preparation.ipynb"}

modules = ["data.py"]

doc_url = "https://fastai.github.io/sperm_whale_bioacoustics/"

git_url = "https://github.com/fastai/sperm_whale_bioacoustics/tree/master/"

def custom_doc_links(name): return None
