# AUTOGENERATED! DO NOT EDIT! File to edit: 02_Data_preparation.ipynb (unless otherwise specified).

__all__ = ['dominicana', 'etp', 'get_independent_vars', 'independent_vars_to_targs', 'drop_last_value', 'get_target',
           'get_clan_membership']

# Cell
from fastai2.data.all import *

dominicana = pd.read_excel('data/Dominicana.xlsx')
etp = pd.read_excel('data/ETP.xlsx')

# Cell
def get_independent_vars(row, start_col=4, n_vals=9):
    vals = [v for v in row[start_col:(start_col+n_vals)].values if v != 0]
    # we want to manually pad the sequence
    # we believe that for a single direction RNN padding the sequence from the left should work better
    return np.pad(vals, (n_vals - len(vals), 0))

# Cell
def independent_vars_to_targs(ary): return ary[-1]

# Cell
def drop_last_value(ary): return ary[:-1]

# Cell
def get_target(row, col_name): return row[col_name]
get_clan_membership = partialler(get_target, col_name='Clan')