# AUTOGENERATED! DO NOT EDIT! File to edit: 04_Pretraining.ipynb (unless otherwise specified).

__all__ = ['Model']

# Cell
from fastai2.basics import *
from fastai2.learner import *
from fastai2.callback.all import *

class Model(Module):
    def __init__(self):
        self.lstm1 = nn.LSTM(input_size=1, hidden_size=256, batch_first=True)
        self.lstm2 = nn.LSTM(input_size=256, hidden_size=256, batch_first=True)
        self.lin = nn.Linear(256, 1)
    def forward(self, x):
        x = x.unsqueeze(-1).to(torch.float32)
        h = self.lstm1(x)[0]
        h = F.relu(h)
        h = self.lstm2(h)[0]
        h = F.relu(h)
        x = self.lin(h[:, -1, :])
        return x